### ISSUE TITLE
Hang, No Errors, Upon Instructing Agent

### ISSUE THREAD

**Issue by CRCODE22** [Josh-XT/Agent-LLM#117]
### Title

When instructing agent it will show no errors and some results but then does nothing anymore 0% python process usage.

### Description

![435645634534523423](https://user-images.githubusercontent.com/88407346/234666651-c7539b68-b638-46bf-8ee2-9df00301bd70.jpg)

### Steps to Reproduce

Instruct agent to Write an engaging tweet about A.I.
Click instruct button
It will show some results and there is no errors but it will do nothing further you will need to kill the app.py and when you repeat the same problem will occur but no errors and it stops at the exact same spot.

### Expected Behavior

To show more results or at least errors as to why it is not showing more results.

### Actual Behavior

It will show some results and there is no errors but it will do nothing further you will need to kill the app.py and when you repeat the same problem will occur but no errors and it stops at the exact same spot.
Also the python process will show 0% processor usage.

### Additional Context

Windows 11
56 GB RAM
Nvidia GTX 3060 12GB
AMD Ryzen 7 3770X 8-Core Processor

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet
- [X] I am using the latest version of the software
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue

**Comment by Josh-XT** [comment]
What provider and model are you using?

**Comment by CRCODE22** [comment]
# =========================
# INSTANCE CONFIG
# =========================
AGENT_NAME=Agent-LLM
WORKING_DIRECTORY=WORKSPACE

# =========================
# TASK SETTINGS
# =========================
OBJECTIVE=Write an engaging tweet about A.I.
INITIAL_TASK=Develop an initial task list.

# =========================
# AI PROVIDER CONFIG
# =========================
AI_PROVIDER=llamacpp
AI_MODEL=vicuna
AI_TEMPERATURE=0.2
MAX_TOKENS=2000

# =========================
# AI PROVIDER: LLAMACPP
# =========================
MODEL_PATH = "D:/one-click-installers/text-generation-webui/models/Pi3141-alpaca-lora-7B-ggml/ggml-model-q4_1.bin"

# =========================
# COMMAND EXTENSIONS
# =========================
COMMANDS_ENABLED=True

# =========================
# MEMORY SETTINGS
# =========================
NO_MEMORY=False
USE_LONG_TERM_MEMORY_ONLY=False

# =========================
# EXTENSIONS: TWITTER
# =========================
#TW_CONSUMER_KEY=my-twitter-consumer-key
#TW_CONSUMER_SECRET=my-twitter-consumer-secret
TW_ACCESS_TOKEN=****
TW_ACCESS_TOKEN_SECRET=*******

**Comment by CRCODE22** [comment]
AI_PROVIDER=llamacpp
AI_MODEL=vicuna
AI_TEMPERATURE=0.2
MAX_TOKENS=2000
# AI PROVIDER: LLAMACPP
MODEL_PATH = "D:/one-click-installers/text-generation-webui/models/Pi3141-alpaca-lora-7B-ggml/ggml-model-q4_1.bin"

**Comment by Josh-XT** [comment]
Sorry for the late follow up - have you had the issues with the latest version?
