### ISSUE TITLE
Hangs on Task List Generation

### ISSUE THREAD

**Issue by Griffin316** [Josh-XT/Agent-LLM#125]
### Title

App hangs on step generating task list.

### Description

I've updated to the latest version, and am running locally not in docker.

When I add a prompt for set agent objective. It is received by app.py and sent to oogabooga.

The window updates with the following, but nothing else comes in.

Starting task with objective: write a tweet about ai.
Executing task 1: Develop a task list.
Starting task with objective: write a tweet about ai.
Executing task 1: Develop a task list.
Starting task with objective: write a tweet about ai.
Executing task 1: Develop a task list.

I provided the log file below

`
INFO:     127.0.0.1:63151 - "POST /api/agent/search%20me/task HTTP/1.1" 200 OK
Starting task with objective: write a tweet about ai.

Executing task 1: Develop a task list.

INFO:     127.0.0.1:63151 - "GET /api/agent/search%20me/task/status HTTP/1.1" 200 OK
search me
write a tweet about ai
INFO:     127.0.0.1:63151 - "GET /api/agent/search%20me/task HTTP/1.1" 200 OK
search me
write a tweet about ai
INFO:     127.0.0.1:63151 - "GET /api/agent/search%20me/task HTTP/1.1" 200 OK
search me
write a tweet about ai
INFO:     127.0.0.1:63151 - "GET /api/agent/search%20me/task HTTP/1.1" 200 OK
search me
write a tweet about ai
INFO:     127.0.0.1:63151 - "GET /api/agent/search%20me/task HTTP/1.1" 200 OK
search me
write a tweet about ai
INFO:     127.0.0.1:63151 - "GET /api/agent/search%20me/task HTTP/1.1" 200 OK
search me
write a tweet about ai
INFO:     127.0.0.1:63151 - "GET /api/agent/search%20me/task HTTP/1.1" 200 OK
search me
write a tweet about ai
INFO:     127.0.0.1:63151 - "GET /api/agent/search%20me/task HTTP/1.1" 200 OK
search me
write a tweet about ai
INFO:     127.0.0.1:63151 - "GET /api/agent/search%20me/task HTTP/1.1" 200 OK
search me
write a tweet about ai
INFO:     127.0.0.1:63151 - "GET /api/agent/search%20me/task HTTP/1.1" 200 OK
search me
write a tweet about ai
INFO:     127.0.0.1:63151 - "GET /api/agent/search%20me/task HTTP/1.1" 200 OK
search me
write a tweet about ai
INFO:     127.0.0.1:63151 - "GET /api/agent/search%20me/task HTTP/1.1" 200 OK
search me
write a tweet about ai
INFO:     127.0.0.1:63151 - "GET /api/agent/search%20me/task HTTP/1.1" 200 OK
INFO:     127.0.0.1:63151 - "GET /api/agent/undefined/command HTTP/1.1" 200 OK
INFO:     127.0.0.1:63151 - "GET /api/agent HTTP/1.1" 200 OK
INFO:     127.0.0.1:63190 - "GET /api/agent/tweeter/command HTTP/1.1" 200 OK
INFO:     127.0.0.1:63191 - "GET /api/agent/search%20me HTTP/1.1" 200 OK
INFO:     127.0.0.1:63151 - "GET /api/agent/search%20me/command HTTP/1.1" 200 OK
INFO:     127.0.0.1:63192 - "GET /api/agent/undefined/command HTTP/1.1" 200 OK
INFO:     127.0.0.1:63193 - "GET /api/agent HTTP/1.1" 200 OK
INFO:     127.0.0.1:63192 - "GET /api/agent/tweeter/command HTTP/1.1" 200 OK
INFO:     127.0.0.1:63193 - "GET /api/agent/search%20me HTTP/1.1" 200 OK
INFO:     127.0.0.1:63192 - "GET /api/agent/search%20me/command HTTP/1.1" 200 OK
search me
write a tweet about ai
INFO:     127.0.0.1:63192 - "GET /api/agent/search%20me/task HTTP/1.1" 200 OK
search me
write a tweet about ai
INFO:     127.0.0.1:63192 - "GET /api/agent/search%20me/task HTTP/1.1" 200 OK
search me
write a tweet about ai
INFO:     127.0.0.1:63192 - "GET /api/agent/search%20me/task HTTP/1.1" 200 OK
INFO:     127.0.0.1:63192 - "GET /api/agent/search%20me/task/status HTTP/1.1" 200 OK
INFO:     127.0.0.1:63192 - "GET /api/agent/search%20me/task/status HTTP/1.1" 200 OK
INFO:     127.0.0.1:63192 - "GET /api/agent/undefined HTTP/1.1" 200 OK
INFO:     127.0.0.1:63192 - "GET /api/agent/undefined/command HTTP/1.1" 200 OK
INFO:     127.0.0.1:63245 - "GET /api/agent HTTP/1.1" 200 OK
INFO:     127.0.0.1:63245 - "GET /api/agent/search%20me HTTP/1.1" 200 OK
INFO:     127.0.0.1:63245 - "GET /api/agent/search%20me/command HTTP/1.1" 200 OK
INFO:     127.0.0.1:63245 - "GET /api/agent/search%20me/task/status HTTP/1.1" 200 OK
INFO:     127.0.0.1:63245 - "GET /api/agent/search%20me/task/status HTTP/1.1" 200 OK
search me
write a tweet about ai
INFO:     127.0.0.1:63245 - "GET /api/agent/search%20me/task HTTP/1.1" 200 OK
search me
write a tweet about ai
INFO:     127.0.0.1:63245 - "GET /api/agent/search%20me/task HTTP/1.1" 200 OK
search me
write a tweet about ai
INFO:     127.0.0.1:63245 - "GET /api/agent/search%20me/task HTTP/1.1" 200 OK
INFO:     127.0.0.1:63246 - "GET /api/agent/undefined/command HTTP/1.1" 200 OK
INFO:     127.0.0.1:63247 - "GET /api/agent HTTP/1.1" 200 OK
INFO:     127.0.0.1:63246 - "GET /api/agent/search%20me HTTP/1.1" 200 OK
INFO:     127.0.0.1:63247 - "GET /api/agent/search%20me/command HTTP/1.1" 200 OK
search me
write a tweet about ai
INFO:     127.0.0.1:63247 - "GET /api/agent/search%20me/task HTTP/1.1" 200 OK
INFO:     127.0.0.1:63476 - "GET /api/agent/undefined/command HTTP/1.1" 200 OK
INFO:     127.0.0.1:63476 - "GET /api/agent HTTP/1.1" 200 OK
INFO:     127.0.0.1:63476 - "GET /api/agent/search%20me HTTP/1.1" 200 OK
INFO:     127.0.0.1:63477 - "GET /api/agent/search%20me/command HTTP/1.1" 200 OK
search me
write a tweet about ai
INFO:     127.0.0.1:63477 - "GET /api/agent/search%20me/task HTTP/1.1" 200 OK
search me
write a tweet about ai
INFO:     127.0.0.1:63477 - "GET /api/agent/search%20me/task HTTP/1.1" 200 OK
`

### Steps to Reproduce

1. write prompt for set agent objective
2. app.py receives the text. Oogabooga receives the request. 
3. the window updates with the following. 

Starting task with objective: write a tweet about ai.
Executing task 1: Develop a task list.
Starting task with objective: write a tweet about ai.
Executing task 1: Develop a task list.
Starting task with objective: write a tweet about ai.
Executing task 1: Develop a task list.

### Expected Behavior

create task list then continue.

### Actual Behavior

task list does not generate

### Python Version

- [ ] Python <= 3.9
- [ ] Python 3.10
- [X] Python 3.11

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet
- [X] I am using the latest version of the software
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue

**Comment by gururise** [comment]
Local model in oogabooga is just not smart enough to handle the prompts.  Can you try with alpaca-65b or open-assistant-30b-llama and see if it helps.

**Comment by Josh-XT** [comment]
Most reports that I've heard so far echo what Guru is saying, you need to use a more advanced model in order to use this.  Some people are having good results with Open Assistant 30B but there may still be some prompt engineering to be done.  To be clear, there is prompt engineering to be done for every model except maybe OpenAI's prompts.  All of my testing while making this has been with OpenAI's API for the sake of speed and best results.  Once we are in a more stable state, I'll most definitely be working on trying to engineer better prompts for the locally hosted models and other contributors are already working on making better prompts for other models.

Stay tuned!  I hope all of that helps.

**Comment by Griffin316** [comment]
Thank you for the reply.

I'll see if I can find some work arounds and will let you know.

I am currently using the Vicuna 13B 4bit model. 

I have a 3060 12gb and a 1080ti 11gb. There's a slight possibility I may get the 30b to work. I'll let you know if there is anything relevant to report.

Thank you for this program and I appreciate your responsiveness.

**Comment by gururise** [comment]
> Thank you for the reply.
> 
> I'll see if I can find some work arounds and will let you know.
> 
> I am currently using the Vicuna 13B 4bit model.
> 
> I have a 3060 12gb and a 1080ti 11gb. There's a slight possibility I may get the 30b to work. I'll let you know if there is anything relevant to report.
> 
> Thank you for this program and I appreciate your responsiveness.

I had limited success with WizardLM-7b; however, the censorship/filtering caused issues.
