### ISSUE TITLE
ASGI error when oppening agent/set agent objective

### ISSUE THREAD

**Issue by NickWithBotronics** [Josh-XT/Agent-LLM#138]
### Title

Clicking start pursuing objective does nothing

### Description

I got it to work 3 times but now the set agent objective page no longer works ive restarted the application multiple times changed up the .env file(removed commands and added them) I tried reinstalling and still nothing, I can still use set agent objective but that's all.
Env:
"
# =========================
# INSTANCE CONFIG
# =========================
AGENT_NAME=Agent-LLM
WORKING_DIRECTORY=WORKSPACE

# =========================
# TASK SETTINGS
# =========================
OBJECTIVE=Write an engaging tweet about AI.
INITIAL_TASK=Develop an initial task list.

# =========================
# AI PROVIDER CONFIG
# =========================
AI_PROVIDER = "oobabooga"
AI_MODEL = "vicuna"
AI_PROVIDER_URI = "http://localhost:5000"
AI_TEMPERATURE = 0.2
MAX_TOKENS = 2096
"

Error code
"
INFO:     127.0.0.1:53058 - "GET /api/agent/Agent-LLM/task/status HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Python311\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 436, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Python311\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Python311\lib\site-packages\fastapi\applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Python311\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Python311\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Python311\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Python311\lib\site-packages\starlette\middleware\cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\Python311\lib\site-packages\starlette\middleware\cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "C:\Python311\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Python311\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Python311\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Python311\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Python311\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\Python311\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\Python311\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "C:\Python311\lib\site-packages\fastapi\routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "C:\Python311\lib\site-packages\fastapi\routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\Users\Nick\Desktop\Agent-LLM-main\app.py", line 241, in get_task_status
    status = CFG.agent_instances[agent_name].get_status()
  File "C:\Users\Nick\Desktop\Agent-LLM-main\AgentLLM.py", line 238, in get_status
    return not self.stop_running_event.is_set()
AttributeError: 'NoneType' object has no attribute 'is_set'
"

According to chat gpt
"
This error message is indicating that there was an exception in an ASGI (Asynchronous Server Gateway Interface) application. Specifically, the error occurred while trying to handle a GET request to "/api/agent/Agent-LLM/task/status". The error code returned was 500 Internal Server Error.

The traceback shows that the root cause of the error is an AttributeError with the message "'NoneType' object has no attribute 'is_set'". This occurred in the file "AgentLLM.py" at line 238, in the method "get_status()".

It appears that there is an issue with the "stop_running_event" attribute of an instance of the "AgentLLM" class. The error message suggests that this attribute is None instead of an object with the expected "is_set()" method.

This could be caused by a number of things, including a bug in the code that creates or manages the "AgentLLM" instances, or a race condition that leads to the attribute being set to None unexpectedly. To fix the error, you will need to investigate the code and find the root cause of the issue with the "stop_running_event" attribute.
"

### Steps to Reproduce

1. Open and load webui, along with agent LLM
2. go to set agent objective
3. On my scrreen no LLM text box shows, only the user text box. (it didnt always do this)
![AgentllmBUG](https://user-images.githubusercontent.com/122953474/234770436-8affa8dc-fe78-4e55-98de-a2649c1ddf77.png)
4. fill in user box
5. hit the button

### Expected Behavior

It supposed to start the agent objective

### Actual Behavior

It gives me this error code in the terminal
"
INFO:     127.0.0.1:53058 - "GET /api/agent/Agent-LLM/task/status HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Python311\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 436, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Python311\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Python311\lib\site-packages\fastapi\applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Python311\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Python311\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Python311\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Python311\lib\site-packages\starlette\middleware\cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\Python311\lib\site-packages\starlette\middleware\cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "C:\Python311\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Python311\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Python311\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Python311\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Python311\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\Python311\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\Python311\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "C:\Python311\lib\site-packages\fastapi\routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "C:\Python311\lib\site-packages\fastapi\routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\Users\Nick\Desktop\Agent-LLM-main\app.py", line 241, in get_task_status
    status = CFG.agent_instances[agent_name].get_status()
  File "C:\Users\Nick\Desktop\Agent-LLM-main\AgentLLM.py", line 238, in get_status
    return not self.stop_running_event.is_set()
AttributeError: 'NoneType' object has no attribute 'is_set'
"

### Additional Context

It might be helpful to know the times i was able to get it to work the command page on the right wouldnt show any commands it was just blank
This shows up sometimes when opening the set agent objective page
![secondbugpic](https://user-images.githubusercontent.com/122953474/234778278-0d508cd7-9ecf-456e-a6ec-4de75f8f398e.png)
opening in brave browser
web ui is using vicuna 1.1v not that it matters because the instruct agent does work also the button to send chat in the "chat with agent" is greyed out and does not work

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [X] Python 3.11

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet
- [X] I am using the latest version of the software
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue

**Comment by NickWithBotronics** [comment]
> Try removing the agents/ and WORKSPACE/ folder, then open the agents in the browser and create a new one by clicking the button, not hitting enter

Just tried that and still the same error

**Comment by Josh-XT** [comment]
No spaces or quotes in your ENV.

```
AI_PROVIDER=oobabooga
AI_MODEL=vicuna
AI_PROVIDER_URI=http://localhost:5000/
AI_TEMPERATURE=0.2
MAX_TOKENS=2096
```

**Comment by Jimisayss** [comment]
I am also getting the same error using the local install. openai is my selected model. I've pulled the repo and downloaded from releases. The docker image is just 404s on every page. 

INFO:     127.0.0.1:57068 - "POST /api/agent/Agent-LLM/task HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 436, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\Users\user\Desktop\Agent-LLM-1.0.14\app.py", line 204, in start_task_agent
    and CFG.agent_instances[agent_name].get_status()
  File "C:\Users\user\Desktop\Agent-LLM-1.0.14\AgentLLM.py", line 238, in get_status
    return not self.stop_running_event.is_set()
AttributeError: 'NoneType' object has no attribute 'is_set'

**Comment by dany-on-demand** [comment]
I think the real issue is 'more helpful error messages' :D

**Comment by NickWithBotronics** [comment]
> No spaces or quotes in your ENV.
> 
> ```
> AI_PROVIDER=oobabooga
> AI_MODEL=vicuna
> AI_PROVIDER_URI=http://localhost:5000/
> AI_TEMPERATURE=0.2
> MAX_TOKENS=2096
> ```
Thank you, I tried this but the results are the same, I can instruct the agent, but I can not use the set agent objective, or else I get the same error.

**Comment by NickWithBotronics** [comment]
Update, I restarted windows, and use chrome instead of brave, and I got the set objective page to work, but only once. after I closed the command prompts and reopened them it stopped working. And is giving me the same error.

**Comment by Josh-XT** [comment]
> 1st Update, I restarted windows, and use chrome instead of brave, and I got the set objective page to work, but only once. after I closed the command prompts and reopened them it stopped working. And is giving me the same error.
> 
> 2nd update
> 
> Every time I restart my computer and give it a simple prompt it does not glitch out. But if I give it longer prompt it refuses to work even after I delete the folders. Seems the error causes issues down the line, or the input gets cached somewhere.
> 
> 3rd update
> 
> Just using this prompt was enough to cause the error, it seems it could be transfering over the name as a .txt file maybe that causes an issue im not quite sure. but this is what the command prompt says
> 
> "OSError: [Errno 22] Invalid argument: 'agents\Agent-LLM\tasks\You are built into a windows computer your objective is to learn how to access the Wikipedia and GitHub using windows command prompt Just by typing a windows command it will automatically be executed You may download command prompt bowsers and anything else that might help you.txt'"
> 
> Then it gives me the same error as before when i try doing anything else. (in order to get it to say the error I had to restart my entire computer, and then reopen everything, and then it does give me that error.)

Yeah it currently just saves the tasks in files, plan to move all of that to a small database later.

I think you're running into the small model problem.  The smaller models don't take too kindly to being given a bunch of options of commands.  The ideal thing to do is give each agent a very small set of commands to work with and narrow scope of work even for the larger models.  Try disabling most of the commands it give it what it might need to complete the tasks you're giving it.
